name: Build and Deploy Docs

on:
  [push]:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/site-deployment.yml"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./docs
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt
      - name: Build
        working-directory: ${{ env.working-directory }}
        run: |
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
